# Generated by Django 5.2.6 on 2025-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.JSONField(default=dict)),
                ('file_size', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
