# Generated by Django 5.2.6 on 2025-09-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
    ]
